
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Company
{

    public Company()
    {

        this.Jobs = new HashSet<Job>();

    }


    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string CompanyWebsite { get; set; }

    public string CompanyInformation { get; set; }

    public string Password { get; set; }

    public string CompanyAddress { get; set; }

    public string CompanyEmail { get; set; }

    public string CompanyPhoneNo { get; set; }

    public byte[] CompanyLogo { get; set; }

    public string CompanyBenefits { get; set; }



    public virtual ICollection<Job> Jobs { get; set; }

}

}
