
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Job
{

    public Job()
    {

        this.Applications = new HashSet<Application>();

        this.Saves = new HashSet<Save>();

    }


    public int JobId { get; set; }

    public int CompanyId { get; set; }

    public string JobTitle { get; set; }

    public string JobRequirement { get; set; }

    public string JobDescription { get; set; }

    public string Location { get; set; }

    public string ShortDescription { get; set; }

    public Nullable<System.DateTime> PostingDate { get; set; }

    public Nullable<System.DateTime> ExpiredDate { get; set; }

    public string ClosingDate { get; set; }

    public Nullable<double> Salary { get; set; }

    public Nullable<int> Test { get; set; }



    public virtual Company Company { get; set; }

    public virtual ICollection<Application> Applications { get; set; }

    public virtual ICollection<Save> Saves { get; set; }

}

}
