
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRIS.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Jobseeker
    {

        public Jobseeker()
        {

            this.Languages = new HashSet<Language>();

            this.Skills = new HashSet<Skill>();

            this.WorkingExperiences = new HashSet<WorkingExperience>();

            this.Applications = new HashSet<Application>();

            this.Saves = new HashSet<Save>();

            this.Tests = new HashSet<Test>();

            this.Qualifications = new HashSet<Qualification>();

        }


        public int JobseekerId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string PhoneNo { get; set; }

        public string Qualification { get; set; }

        public string FieldOfStudy { get; set; }

        [Required]
        public string PreferredLocation { get; set; }

        [Required]
        public string PreferredField { get; set; }

        public byte[] Resume { get; set; }

        [Required]
        public string Address { get; set; }

        public string JobseekerGender { get; set; }

        public byte[] Picture { get; set; }

        [Required]
        public Nullable<double> PreferredSalary { get; set; }



        public virtual ICollection<Language> Languages { get; set; }

        public virtual ICollection<Skill> Skills { get; set; }

        public virtual ICollection<WorkingExperience> WorkingExperiences { get; set; }

        public virtual ICollection<Application> Applications { get; set; }

        public virtual ICollection<Save> Saves { get; set; }

        public virtual ICollection<Test> Tests { get; set; }

        public virtual ICollection<Qualification> Qualifications { get; set; }

        internal void CreatePhoneNumbers(int count = 1)
        {
            for (int i = 0; i < count; i++)
            {
                Languages.Add(new Language());
            }
        }

        internal void CreatePhoneNumbers2(int count = 1)
        {
            for (int i = 0; i < count; i++)
            {
                Qualifications.Add(new Qualification());
            }
        }

        internal void CreatePhoneNumbers3(int count = 1)
        {
            for (int i = 0; i < count; i++)
            {
                Skills.Add(new Skill());
            }
        }

        internal void CreatePhoneNumbers4(int count = 1)
        {
            for (int i = 0; i < count; i++)
            {
                WorkingExperiences.Add(new WorkingExperience());
            }
        }
    }

}
