
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Save
{

    public int SaveId { get; set; }

    public int JobseekerId { get; set; }

    public int JobId { get; set; }



    public virtual Jobseeker Jobseeker { get; set; }

    public virtual Job Job { get; set; }

}

}
