

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRIS.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SignUpEntities : DbContext
{
    public SignUpEntities()
        : base("name=SignUpEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Jobseeker> Jobseekers { get; set; }

    public DbSet<Language> Languages { get; set; }

    public DbSet<Skill> Skills { get; set; }

    public DbSet<WorkingExperience> WorkingExperiences { get; set; }

    public DbSet<Application> Applications { get; set; }

    public DbSet<Company> Companies { get; set; }

    public DbSet<Save> Saves { get; set; }

    public DbSet<Job> Jobs { get; set; }

    public DbSet<PreferredLocation> PreferredLocations { get; set; }

    public DbSet<Test> Tests { get; set; }

    public DbSet<Qualification> Qualifications { get; set; }

    public DbSet<TestQuestion> TestQuestions { get; set; }

    public DbSet<TestAnswer> TestAnswers { get; set; }

}

}

