
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PRIS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TestQuestion
{

    public TestQuestion()
    {

        this.TestAnswers = new HashSet<TestAnswer>();

    }


    public int Id { get; set; }

    public int Part { get; set; }

    public string Question { get; set; }



    public virtual ICollection<TestAnswer> TestAnswers { get; set; }

}

}
